export const appPermissions = {
    none: '00',
    posts: "1",
    comments: "2",
    users: "3",
    events: "4",
    offices: "5",
    roles: "6",
    appPermissions: "7",
    categories: "8",
    partners: "9",
    reset_user_password: "10",
    newsletter: "11",
    services: "12",
    devis: "13",
    quoteRequests: "13",
    team: "14",
    likes: "15",
    post_likes: "15",
    db_logs: "16",
    jobOffers: "17",
    dashboard: "18",
    reports: "19",
    visitor_accounts: "20",
    menu_visibility: "21",
    cotation: "22",
    appelOffre: "23",
    certifications: "24",

    users_assign_roles: "00",
    users_permissions: "00",
    settings: "00",
    notifications: "00",
    updates: "00",
}
