export const appPermissions = {
    none: '00',
    posts: "1",
    comments: "2",
    users: "3",
    events: "4",
    offices: "5",
    roles: "6",
    appPermissions: "7",

    partners: "00",
    services: "00",
    menu_visibility: "00",
    quote_requests: "00",
    likes: "00",
    categories: "00",
    newsletter: "00",
    dashboard: "00",
    users_assign_roles: "00",
    users_permissions: "00",
    reports: "00",
    settings: "00",
    notifications: "00",
    updates: "00",
}
