const urls =  {
    openOffices: '/open/offices',
    openPartners: '/open/partners',
    openServices: '/open/services',
    openPosts: '/open/posts',
    openEvents: '/open/events',
    openNewsletters: '/open/newsletters',
    openJobOffers: '/open/job-offers',
    openTeams: '/open/teams',
    openCategories: '/open/categories',

    login: '/login',
    logout: '/api/logout',
    users: '/api/users',
    roles: '/api/roles',
    offices: '/api/offices',
    appPermissions: '/api/app-permissions',
    rolesPermissions: '/api/role-default-permissions',
    categories: '/api/categories',
    partners: '/api/partners',
    services: '/api/services',
    posts: '/api/posts',
    postLikes: '/api/post-likes',
    postComments: '/api/post-comments',
    events: '/api/events',
    newsletters: '/api/newsletters',
    jobOffers: '/api/job-offers',
    teams: '/api/teams',
}

export default urls
