import {UseGetCotations} from "../services/queries/ServicesQueries.ts";

const urls =  {
    openOffices: '/open/offices',
    openPartners: '/open/partners',
    openServices: '/open/services',
    openPosts: '/open/posts',
    openEvents: '/open/events',
    openNewsletters: '/open/newsletters',
    openJobOffers: '/open/job-offers',
    openTeams: '/open/teams',
    openCategories: '/open/categories',
    openQuoteRequests: '/open/quote-requests',
    openVisitors: '/open/visitor-accounts',
    openPostComments: '/open/post-comments',
    openPostLikes: '/open/post-likes',

    connectedVisitors: '/visitor/visitor-accounts',

    login: '/login',
    logout: '/api/logout',
    users: '/api/users',
    roles: '/api/roles',
    offices: '/api/offices',
    dashboard: '/api/dashboard',
    appPermissions: '/api/app-permissions',
    rolesPermissions: '/api/role-default-permissions',
    categories: '/api/categories',
    partners: '/api/partners',
    services: '/api/services',
    quoteRequests: '/api/quote-requests',
    cotations: '/api/cotations',
    cotationStatus: '/api/cotation-status',
    callOffers: '/api/call-offers',
    callOfferTasks: '/api/call-offer-tasks',
    posts: '/api/posts',
    postLikes: '/api/post-likes',
    postComments: '/api/post-comments',
    events: '/api/events',
    newsletters: '/api/newsletters',
    jobOffers: '/api/job-offers',
    teams: '/api/teams',
    visitors: '/api/visitor-accounts',
}

export default urls
